name: automatic deploy

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup pnpm
        uses: pnpm/action-setup@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: ci
        run: pnpm i
      - name: build
        run: pnpm run build
      - name: deploy
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
